### ISSUE TITLE
what kind of formatted.xlsx is needed?

### ISSUE THREAD

**Issue by Huleyun** [glenjasper/download-papers#1]
Hello glenjasper,

I am now trying to use this code to download papers through DOIs, but I get some errors when I try to run this code. What kind of format is needed in the .xlsx document? And can you send me an example file?

**Comment by glenjasper** [comment]
Good morning, sorry for replying late, I was traveling. You can use this excel file as a model.

Command: python3 download_papers.py -i papers.xlsx

Glen
[papers.xlsx](https://github.com/glenjasper/download-papers/files/7575814/papers.xlsx)
,

**Comment by Huleyun** [comment]
Thanks for your reply, I will try it again!!
